### ISSUE TITLE
Given, When, Then descriptions

### ISSUE THREAD

**Issue by nitro52** [searls/jasmine-given#48]
Hi, 
I really love the Given, When, Then approach to splitting up your tests, but a huge part of why this is so useful in other frameworks is that it gives you the ability to describe the actions in a human readable way. It would be great if we could add an optional description string that then gets reported in the test results. For example

describe("assigning stuff to this", function() {
  Given("I have the number 24", function() { this.number = 24; });
  Given("I increment by one", function() { this.number++; });
  When("I multiply by two", function() { this.number *= 2; });
  Then("I should get 50", function() { return this.number === 50; });
});

Then it would be good to see in the test results something like this

assigning stuff to this - Passed
----- Given I have the number 24 - Passed
----- Given I increment by one  - Passed
----- When I multiply by two  - Passed
----- Then I should get 50  - Passed

Or ideally replace subsequent actions with And 

assigning stuff to this - Passed
----- Given I have the number 24 - Passed
----- And I increment by one  - Passed
----- When I multiply by two  - Passed
----- Then I should get 50  - Passed

**Comment by searls** [comment]
Sorry, @nitro52 but I'm :-1: on this. When @jimweirich designed rspec-given, a big part of his motivation was a rejection of the english-language-to-code translation made popular by Cucumber & RSpec. The reason is pretty straightforward, because in practice after you're comfortable writing a lot of tests you see these descriptors used in one of two ways:

First way:

``` javascript
it('should add 2 and 2 and get four', function(){
  expect(2 + 2).toEqual(4);
});
```

In the above, the text adds absolutely nothing, the code is readable, and if anything the text is a liability/carrying cost (just like a code comment is) in that it could become incorrect without anyone noticing in the future. 

The other thing you see:

``` javascript
it('should send our accountants the TPS report for June', function(){
  expect(sillyNonsense("2138-GPL-4i2").functoCode).toEqual("sent");
});
```

In this case, the text description is a coping mechanism around a junky API that's unclear and not helpful. Rather than give ourselves the salve of a textual description to paper over our obtuse & confusing API, the goal of -given libraries is to make that un-obviousness stick out like a sore thumb.

That way, as a developer when I read a test that says:

``` coffeescript
Then ->  sillyNonsense("2138-GPL-4i2").functoCode == "sent"
```

I'm rightfully left scratching my head when I read the above, and hopefully driven to clean the API up tremendously to make it say what it's doing in a meaningful way.

**Comment by ronen** [comment]
@searls I'm kinda inbetween, and I think @nitro52 might actually be on to something...

I agree with `Then { expect(2+2).toEqual 4 }`  and that's what I do pretty much 100% of the time.  But that said, the current code *does* allow you provide labels to Then clauses if you really want to (https://github.com/searls/jasmine-given#it-style-test-labels).  I never bother with it, since I'd just as soon look at the ugly code as have to make up words.

Looking though at Givens and Whens, I have found that I do still have to type a bunch of words for contexts.  Standard pattern is

```coffeescript
context "given foo is true", ->
  Given -> @foo = true 
  
  context "when I click on a bug", ->
      When -> $.find(".bug").click()
```

Since words are still needed to describe what's happening with the Given's and When's, maybe something like @nitro52's proposal could make that cleaner?  This does actually seem cleaner:

```coffeescript
context ->
    Given "foo is true" -> @foo = true

    context ->
      When "I click on a bug", -> $.find(".bug").click()

      Then -> expect(@happiness()).to beTrue
```

And once we've done that...  There are some times the Given or When code is clear and terse, and then you should be able to leave off the label and it'd be autogenerated same as for Then's.  E.g.

```coffeescript
context ->
    Given -> @foo = true

    context ->
      When "I click on a bug", -> $.find(".bug").click()

      Then -> expect(@happiness()).to beTrue
```

would autogenerate
```
--- Given @foo = true
  --- When I click on a bug
    --- Then expect(@happiness()).to beTrue
```

And voila!  A step closer to the utopian ideal of English-free tests!

BTW another benefit to allowing labels everywhere is that it will make the library and methodology more accessible to newbies.  I suspect many people who first encounter Given/When/Then, either here or in @jimweirich's rspec gem can be put off by the lack of text labels.  In fact one of the first things I did was submit a PR to allow them, which @jimwerich rejected.   I think that's actually being overly principled.... it does little harm to allow people to use them (trivial code addition), and provides a gentle introduction to Given/When/Then.  And many people (like myself) would quickly enough discover that their English labels aren't necessary, and laziness (if nothing else) would take over and they'd stop bothering, and their tests would become better.  That's what happened to me, anyway.

**Comment by searls** [comment]
I appreciate your perspective @ronen, particularly because you acknowledge the multiple a-ha moments that might come as someone grows comfortable with this testing style. My view on this (and partly b/c I've been thinking through https://github.com/testdouble/testdouble.js) is that one benefit of being a little, hyper-opinionated contender is that the message is clearer when it's sharper and pointier.

Put a different way, if rspec-given hadn't been so strict, it wouldn't have prompted me to ask Jim "hey, why can't I do this?" And in every case he'd already considered my thing, shot it down very kindly, and while my ego was bruised it was usually something I came around to.

In short:
* I'd remove the Then/And description / label option if I could without breaking back-compat
* If you _really want to_, you can provide a `Given "whatever you want", -> ` right now, and it'll just set `this["whatever you want"]` to whatever the function evaluates too. There's not a reporter for that, but I don't think the tool will blow up if you insist.
* I actually like having the english language show up in those `context` calls like you have above because explaining the context of the test is exactly what's _not_ communicated by the code, and usually the one place where it's helpful.

Thanks for chiming in. I appreciate your perspective and it made me pause for sure.
