### ISSUE TITLE
Working with Angular2

### ISSUE THREAD

**Issue by 2bigO** [searls/jasmine-given#51]
Hi,

Was wondering if it'd be possible to use `jasmine-given` within Angular2?
Angular2 [uses jasmine](https://angular.io/docs/ts/latest/guide/testing.html#!#jasmine-101) as the foundation for it's testing framework, there is _forthcoming_ chapter (Test a Component in the DOM) [in docs](https://angular.io/docs/ts/latest/guide/testing.html) on how helpers could be integrated, though I need testing in a production app now and docs doesn't seems to be Angular's top priority right now :(

Any help is very much appreciated.

**Comment by searls** [comment]
There's no reason that this library wouldn't work with Angular, but I don't think it'd be appropriate for us to invest the time in examples specific to each framework. I recommend giving it a try and see what you run into, then open issues if jasmine-given is the root cause of any problems you encounter.
